### ISSUE TITLE
-side is not working as expected & sometimes throws an error

### ISSUE THREAD

**Issue by ahmedelgabri** [mhinz/vim-grepper#180]
I'm getting this error whenever I use `-side` & search while on an empty buffer or a Startify buffer.

```
Error detected while processing function <SNR>134_on_exit[4]..<SNR>134_finish_up[49]..<SNR>134_side[1]..<SNR>134_side_create_window:
line   33:
E484: Can't open file <empty>
Press ENTER or type command to continue
```

But if I run the same command on a non-empty buffer it opens this instead. Which is the Quickfix & the side buffer but at the bottom of the window

<img width="997" alt="screenshot 2018-10-13 at 20 25 22" src="https://user-images.githubusercontent.com/63876/46908650-333ad280-cf26-11e8-9f9b-81db4aeb2c7a.png">

This is my grepper settings

```vim
command! Todo :Grepper
      \ -side
      \ -noprompt
      \ -tool git
      \ -grepprg git grep -nIi '\@\?\(TODO\|FIXME\|NOTE)'

augroup MyGrepper
  autocmd!
  autocmd FileType GrepperSide
      \  silent execute 'keeppatterns v#'.b:grepper_side.'#>'
      \| silent normal! ggn
      \| setl wrap
augroup END

xmap gs <plug>(GrepperOperator)
vmap gs <Plug>(GrepperOperator)
nnoremap \ :silent! packadd vim-grepper<CR><BAR>:Grepper -side -tool rg -query --hidden<SPACE>
```

**Comment by mhinz** [comment]
Your `\` mapping is wrong. `-query` is used for the actual search query, not for options. I'll alter the doc to make this point clearer.

Use something like this instead:

```vim
nnoremap \ :silent! packadd vim-grepper<cr><bar>:Grepper -side -noprompt -tool rg -grepprg rg -H --vimgrep --no-heading --hidden<space>
```

This fixes the mapping but is quite long. You might want to remove the `-nompromt` and use Grepper's prompt instead. (And maybe even `let g:grepper.simple_prompt = 1` for an even shorter prompt.)

---

I think `:packadd` already sources `plugin/grepper.vim`, so an alternative would be:

```vim
nnoremap \ :silent! packadd vim-grepper<cr><bar>let g:grepper.rg.grepprg .= ' --hidden'<bar>Grepper -side -tool rg --query<space>
```

HTH

**Comment by mhinz** [comment]
I fixed the doc. Thanks for bringing this up! ✨

**Comment by ahmedelgabri** [comment]
Thanks, I tried both but it seems the second one deosn't work

```vim
nnoremap \ :silent! packadd vim-grepper<cr><bar>let g:grepper.rg.grepprg .= ' --hidden'<bar>Grepper -side -tool rg --query<space>
```

All I get back is this in the command bar at the bottom

```
:silent! packadd vim-grepper
```

**Comment by ahmedelgabri** [comment]
I found the issue, you missed the `:` before the `let` :) works fine, thanks again.
