### ISSUE TITLE
Add support for ripgrep

### ISSUE THREAD

**Issue by gauteh** [mhinz/vim-grepper#64]
Would be great with support for ripgrep: https://github.com/BurntSushi/ripgrep

**Comment by mhinz** [comment]
`:Grepper -tool rg` and `:Rg` should be a thing now!

**Comment by gauteh** [comment]
Thanks,

but I can't get :Rg to work.. and :GrepperRg also just gives me the
invalid command messages in the QF window.

rg as a tool seems to work!

-g

**Comment by mhinz** [comment]
Can you post that message? Are you on Windows by any chance?

**Comment by gauteh** [comment]
I'm on Arch Linux.

It turns out that `:GrepperRg` without arguments is what causes problems:
![2016-09-27-113516_668x365_scrot](https://cloud.githubusercontent.com/assets/56827/18867985/c75134d6-84a6-11e6-85e9-3358389efeb0.png)

However, running it with an argument does nothing.. though if I run the `rg` command on the command line it quickly finishes for the same query.

**Comment by gauteh** [comment]
Same for running it through `:Grepper`, regular `grep` works, but has some issues if no results are found. I also get some on_exit error with rg through :Grepper some times..

**Comment by mhinz** [comment]
Okay, I pushed 2 new commits. One should makes the `:Grepper*` commands take at least one argument and the other should avoid that error on `on_exit`.

Can you paste the output of a sample `rg --no-heading --vimgrep -i foo`? What's the output of `rg --version`? I'm using 0.2.0.

**Comment by gauteh** [comment]
```
[strange vim-grepper](master) $ rg --no-heading --vimgrep -i foo
README.md:34:41:  command for convenience. `:GrepperAg 'foo bar' test/` does just what you would
README.md:131:11:Now `:GG 'foo bar' *.txt` would search all text files for the string "foo bar"
README.md:131:71:Now `:GG 'foo bar' *.txt` would search all text files for the string "foo bar"
README.md:132:10:and `:Ag foo` would search for "foo", but only in the current file. (Vim will
README.md:132:33:and `:Ag foo` would search for "foo", but only in the current file. (Vim will
test/feature/flags.vader:6:72:Execute (:Grepper -noprompt -tool ag -grepprg ag --column --nogroup -s Foo include):
test/feature/flags.vader:7:64:  Grepper -noprompt -tool ag -grepprg ag --column --nogroup -s Foo include
test/feature/flags.vader:10:59:  AssertEqual w:quickfix_title, 'ag --column --nogroup -s Foo include '
test/feature/flags.vader:13:82:Execute (:Grepper -noprompt -noswitch -tool ag -grepprg ag --column --nogroup -s Foo include):
test/feature/flags.vader:14:74:  Grepper -noprompt -noswitch -tool ag -grepprg ag --column --nogroup -s Foo include
test/feature/flags.vader:21:80:Execute (:Grepper -noprompt -noopen -tool ag -grepprg ag --column --nogroup -s Foo include):
test/feature/flags.vader:22:72:  Grepper -noprompt -noopen -tool ag -grepprg ag --column --nogroup -s Foo include
test/feature/flags.vader:27:86:Execute (:Grepper -noprompt -noopen -jump -tool ag -grepprg ag --column --nogroup -s Foo include):
test/feature/flags.vader:28:78:  Grepper -noprompt -noopen -jump -tool ag -grepprg ag --column --nogroup -s Foo include
test/feature/flags.vader:31:30:  AssertEqual getline('.'), 'Foo: This is just a random'
test/include/test.txt:1:1:Foo: This is just a random
test/include/test.txt:5:1:foo bar quux
autoload/grepper.vim:268:9:    " \bfoo\b -> \<foo\> Assume only one pair.
autoload/grepper.vim:268:20:    " \bfoo\b -> \<foo\> Assume only one pair.
```

```
[strange vim-grepper](master) $ rg --version
0.2.1
```

**Comment by gauteh** [comment]
I still don't get any results from the `:GrepperRg` command nor by using `:Grepper` and using the `rg` tool. Sometimes I get the `No matches found.` message.

**Comment by mhinz** [comment]
Yea, I'm not sure what that problem is about yet. Actually someone else has a similar problem, and I'm beginning to think it's Vim's fault since its async capabilities are quite new.

On Neovim, everything works. On Vim, `:GrepperGit` and `:GrepperGrep` and `:GrepperAg` work just fine, but `:GrepperRg` and `:GrepperAck` yield problems similar to yours. It looks as if the async process starts but never returns.

You can test this:

```
:let w:testing = 1
:GrepperRg foo

```

This should work, since it forces a synchronous search.

**Comment by gauteh** [comment]
Yup, w:testing works fine. Is that local to grepper or are other plugins/vim sensitive to that option?

**Comment by mhinz** [comment]
It's a Grepper thing. It's a hidden variable that is used by the testing suite, since TravisCI has problems with asynchronous searches.

Thanks for the feedback so far.

**Comment by gauteh** [comment]
Ok :) thanks!

**Comment by mhinz** [comment]
All following posts will be done in #65 since it's the same issue.
